#!/usr/bin/bash

CLIP_PATH="`winepath --windows \"$1\"`"

echo $CLIP_PATH
export PROTON_PATH=$(cat ~/.config/csprc | grep PROTON_PATH | cut -d '=' -f 2)
echo $PROTON_PATH
export STEAM_COMPAT_DATA_PATH=$(cat ~/.config/csprc | grep STEAM_COMPAT_DATA_PATH | cut -d '=' -f 2)
export STEAM_COMPAT_CLIENT_INSTALL_PATH=$(cat ~/.config/csprc | grep STEAM_COMPAT_CLIENT_INSTALL_PATH | cut -d '=' -f 2)

echo "Setting Windows version to win81..."
$PROTON_PATH/proton run winecfg -v win81
if [ $? -ne 0 ]; then
    echo "Failed to set Windows version to win81"
    exit 1
fi

echo "Starting CSP..."
if [ -z "$CLIP_PATH" ]
then
    $PROTON_PATH/proton run $STEAM_COMPAT_DATA_PATH/pfx/drive_c/Program\ Files/CELSYS/CLIP\ STUDIO\ 1.5/CLIP\ STUDIO\ PAINT/CLIPStudioPaint.exe
else
    $PROTON_PATH/proton run $STEAM_COMPAT_DATA_PATH/pfx/drive_c/Program\ Files/CELSYS/CLIP\ STUDIO\ 1.5/CLIP\ STUDIO\ PAINT/CLIPStudioPaint.exe "$CLIP_PATH"
fi

